// src/modules/characteristics/index.ts
export * from './characteristics.module'
export * from './characteristics.controller'
export * from './characteristics.service'
export * from './dto/create-characteristic.dto'
export * from './dto/update-characteristic.dto'
export * from './dto/characteristic-response.dto'
export * from './dto/characteristic-value.dto'
export * from './dto/characteristics-filter.dto'
export * from './interfaces/characteristic.interface'
